spring.application.name=grifo-asto-core
# Puerto del servidor
server.port=8080


# JPA
spring.jpa.database=postgresql
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Datos a PostgreSQL in local
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.datasource.url=jdbc:postgresql://localhost:5433/grifodb
# spring.datasource.username=postgres
# spring.datasource.password=admin123

# Datos a AWS RDS for railway
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://maglev.proxy.rlwy.net:42429/railway
spring.datasource.username=postgres
spring.datasource.password=jjWtQvVrsQtwsYybKMvHBaGxJbNVPAfq
spring.datasource.port=42429

# JWT Configuration
jwt.secret=5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437
jwt.expiration=7200000
# 7200000 ms = 120 minutes